version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: shared_between_nodes
            RABBITMQ_DEFAULT_USER: worker
            RABBITMQ_DEFAULT_PASS: worker
        ports:
            - 5672:5672
            - 15672:15672
    worker_1:
        image: worker_app
        container_name: worker_app
        environment:
            WORKER_APP_RABBITMQ_HOST: rabbitmq
            WORKER_APP_RABBITMQ_PORT: 5672
            WORKER_APP_RABBITMQ_QUEUE: incoming_uploads
            WORKER_APP_RABBITMQ_USERNAME: worker
            WORKER_APP_RABBITMQ_PASSWORD: worker
        restart: always
