name: Deploy worker app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
        
    - uses: actions/checkout@v2
    - name: Build and push image to private repository
      uses: docker/build-push-action@v1
      with:
        registry: localhost:5000
        repository: cyphernet/worker-app:latest
        tag_with_ref: false